spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: CLIENT_ID
  mail:
    password: NEED_TO_INPUT
custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUser:
              oauthId: oauthId
              nickname: nickname
  jwt:
    secretKey: aebjhfwajehvjasbdluwevdasvdfjlegavksdjgvalkejgsf123u4v123123123b23231sse2234ksn0faj32